modified nas bootscript to use functions in start
git-svn-id: svn://svn.linuxfromscratch.org/BLFS/trunk@2899 af4574ff-66df-0310-9fd7-8a98e5e911e0

diff --git a/bootscripts/blfs/init.d/nas b/bootscripts/blfs/init.d/nas
--- a/bootscripts/blfs/init.d/nas
+++ b/bootscripts/blfs/init.d/nas
@@ -13,19 +13,20 @@
 case "$1" in
         start)
                 echo "Starting the Network Audio System Server..."
-                pidof nasd
-                if test $? = "0"
-                then
-                        print_status warning running
-                else
-                        /usr/X11R6/bin/nasd -aa &
-                        pidof /usr/X11R6/bin/nasd
-                        if test $? = "0" ; then
-                                print_status success
-                        else
-                                print_status failure
-                        fi
-                fi
+		loadproc /usr/X11R6/bin/nasd -aa -b
+#                pidof nasd
+#                if test $? = "0"
+#                then
+#                        print_status warning running
+#                else
+#                        /usr/X11R6/bin/nasd -aa &
+#                        pidof /usr/X11R6/bin/nasd
+#                        if test $? = "0" ; then
+#                                print_status success
+#                        else
+#                                print_status failure
+#                        fi
+#                fi
 		;;
 
         stop)
