Updated nfs related bootscripts. Removed portmap in favor of rpcbind. Updated instructions for rpcbind and nfs-utils.
git-svn-id: svn://svn.linuxfromscratch.org/BLFS/trunk@9048 af4574ff-66df-0310-9fd7-8a98e5e911e0

diff --git a/bootscripts/blfs/init.d/netfs b/bootscripts/blfs/init.d/netfs
--- a/bootscripts/blfs/init.d/netfs
+++ b/bootscripts/blfs/init.d/netfs
@@ -5,29 +5,27 @@
 # Description : Mount network filesystems
 #
 # Author      : Nathan Coulson - conathan@conet.dyndns.org
-#		DJ Lucas - dj@linuxfromscratch.org
+#               DJ Lucas - dj@linuxfromscratch.org
 #
 # Version     : LFS 7.0
 #
 ########################################################################
 
 ### BEGIN INIT INFO
-# Provides:		nfs mounts
-# Required-Start:	network
+# Provides:    nfs mounts
+# Required-Start: nfs-client nfs-server
 # Should-Start:
-# Required-Stop:	sendsignals
+# Required-Stop:  sendsignals
 # Should-Stop:
-# Default-Start:	3 4 5
-# Default-Stop:		0 1 2 6
-# Short-Description:	Mounts network volumes.
-# Description:		Mounts anything marked as _netdev, and umounts
-#			any mounted _netfs,smbfs,ncpfd,coda, nfs
-#			volumes
-# X-LFS-Provided-By:	LFS
+# Default-Start:  3 4 5
+# Default-Stop:   0 1 2 6
+# Short-Description: Mounts network volumes.
+# Description:    Mounts anything marked as _netdev, and umounts
+#        any mounted _netfs, smbfs, ncpfd,coda, or nfs volumes
+# X-LFS-Provided-By: LFS
 ### END INIT INFO
 
 . /lib/lsb/init-functions
-# Begin $rc_base/init.d/netfs
 
 #$LastChangedBy$
 #$Date$
@@ -44,20 +42,18 @@ case "$1" in
 
    stop)
       log_info_msg "Unmounting network volumes..."
+
       # The following line obtains a list from the output of
       # mount for all netfs types and anything that was
       # mounted with the _netdev option.
       NETMOUNTS=`/bin/mount \
-        | /bin/grep '_netdev\|smbfs\|ncpfs\|coda\|nfs' \
-        | /usr/bin/cut -d " " -f 3 | /bin/sed ':a;$!N;s/\n/ /;ta'`
+         | /bin/grep '_netdev\|smbfs\|ncpfs\|coda\|nfs' \
+         | /usr/bin/cut -d " " -f 3 | /bin/sed ':a;$!N;s/\n/ /;ta'`
 
       # Check to see if anything was listed from above
       # (see if anything is actually needs to be unmounted)
-      if [ x"$NETMOUNTS" != x ]
-      then
+      if [ x"$NETMOUNTS" != x ]; then
          # There is something mounted
-         # terminate the echo -n above
-         echo ""
 
          # Try and stop processes the nice way
          # (probably won't work in most cases)
@@ -67,9 +63,8 @@ case "$1" in
          # did, then give 3 seconds for things to exit
          # the nice way before killing them off.
          # This one will work all of the time!
-         if [ $? = 0 ]
-         then
-            /bin/sleep 3
+         if [ $? = 0 ]; then
+            /bin/sleep ${KILLDELAY:-3}  # Default is 3, not minus 3
             /bin/fuser -km $NETMOUNTS > /dev/null
          fi
 
@@ -79,37 +74,33 @@ case "$1" in
          # certain that netmounts without the _netdev option
          # will still get unmounted.
          /bin/umount -af -O _netdev
-         # save the retval
-            if [ $? != 0 ]
-            then
-                NERRVAL=1
-            fi
+
+         # Save the return value
+         NERRVAL=$?
 
          # Now catch the rest of the network filesystems
          # by fstype.  This list can be extended later as
          # more network filesystems are supported by mount.
-         /bin/umount -af -t coda,ncpfs,nfs,smbfs
-         if [ $? = 0 ]
-         then
-            [ -z $NERRVAL ]
-            evaluate_retval
+         /bin/umount -af -t coda,ncpfs,nfs,smbfs,nfsd
+
+         if [ $? = 0  -a  $NERRVAL = 0 ]; then
+           (exit 0)
          else
-            # make certain that we return an error
-            /bin/false
-            evaluate_retval
+           (exit 1)
          fi
+
+         evaluate_retval
+
       else
          # There is nothing mounted
-         log_info_msg "No network volumes mounted!"
-         # print a nice '[  OK  ]' message
-         echo_ok
+         log_success_msg2 "No network volumes mounted!"
       fi
       ;;
 
-   *)
+*)
       echo "Usage: $0 {start|stop}"
       exit 1
       ;;
 esac
 
-# End $rc_base/init.d/netfs
+# End /etc/init.d/netfs
