Update to qpopper4.1.0
git-svn-id: svn://svn.linuxfromscratch.org/BLFS/trunk@9947 af4574ff-66df-0310-9fd7-8a98e5e911e0

diff --git a/bootscripts/blfs/init.d/qpopper b/bootscripts/blfs/init.d/qpopper
--- a/bootscripts/blfs/init.d/qpopper
+++ b/bootscripts/blfs/init.d/qpopper
@@ -1,69 +1,67 @@
 #!/bin/sh
-# Description: The qpopper program provides Post Office Protocol services
-#              to users.
+########################################################################
+# Begin /etc/init.d/qpopper
 #
-# Processname: popper
-# config: /etc/mail/qpopper.conf
+# Description : Provide Post Office Protocol (POP3) services
+#
+# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
+#
+# Version     : LFS 7.2
+#
+########################################################################
 
-# Based on sysklogd script from LFS-3.1 and earlier.
-# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
+### BEGIN INIT INFO
+# Provides:            qpopper
+# Required-Start:      $syslog $local_fs $network
+# Should-Start:        
+# Required-Stop:       $network
+# Should-Stop:
+# Default-Start:       3 4 5
+# Default-Stop:        0 1 2 6
+# Short-Description:   Starts qpopper (POP3) process.
+# Description:         Starts qpopper (POP3) process.
+# X-LFS-Provided-By:   BLFS
+### END INIT INFO
+
+. /lib/lsb/init-functions
 
 #$LastChangedBy$
 #$Date$
 
-. /etc/sysconfig/rc
-. $rc_functions
-
 CONFIG=/etc/mail/qpopper.conf
+QPOPPER=/usr/sbin/popper
 #PORT=110
 
-[ -f /usr/sbin/popper ] || exit 0
-
-RETVAL=0
-prog="qpopper"
-
-
-start()
-{
-   if [ ! -f $CONFIG ]
-   then
-      echo "$prog not started.  $CONFIG missing!"
-      exit 1
-   fi
-   echo -n $"Starting $prog: "
-   loadproc /usr/sbin/popper $PORT -f $CONFIG
-   echo
-   RETVAL=$?
-   return $RETVAL
-}
-
-stop()
-{
-   echo -n $"Shutting down $prog: "
-   killproc popper
-   RETVAL=$?
-   echo
-   return $RETVAL
-}
-
+[ -x $QPOPPER ] || exit 0
 
 case "$1" in
   start)
-    start
-        ;;
-  stop)
-    stop
-        ;;
-  restart)
-        stop
-        start
-        RETVAL=$?
-        ;;
-  *)
-        echo "Usage: /etc/init.d/qpopper{start|stop|restart}"
+     log_info_msg "Starting Qpopper daemon..."
+     
+     if [ ! -f $CONFIG ]; then
+        log_failure_msg2 "$CONFIG missing!"
         exit 1
+     fi
+     
+     start_daemon $QPOPPER $PORT -f $CONFIG
+     evaluate_retval
+     ;;
+
+  stop)
+     log_info_msg "Stopping Qpopper..."
+     killproc $QPOPPER 
+     evaluate_retval
+     ;;
+
+  restart)
+    $0 stop
+    $0 start
+    ;;
+
+  *)
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
+    ;;    
 esac
 
-exit 0
-
-# End $rc_base/init.d/qpopper
+# End /etc/init.d/qpopper
