Update to autofs-5.0.6
git-svn-id: svn://svn.linuxfromscratch.org/BLFS/trunk/bootscripts@10009 af4574ff-66df-0310-9fd7-8a98e5e911e0

diff --git a/blfs/init.d/autofs b/blfs/init.d/autofs
--- a/blfs/init.d/autofs
+++ b/blfs/init.d/autofs
@@ -1,193 +1,157 @@
 #!/bin/bash
+########################################################################
+# Begin autofs
 #
-# Autofs Boot Script
+# Description : Start daemon for automounting file systems
 #
-# Filename:     /etc/rc.d/init.d/autofs
+# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
 #
-# Author:       Bryan Mason <bmason@bmason.com>
+# Version     : LFS 7.2
 #
-# Edit History:
+# Notes       : Updates to autofs distributed start script to make
+#               compatible with BLFS
 #
-# Date         Author        Action
-# ----------------------------------------------------------------------
-# 20 Jan 2004  B. Mason      Created by modifying original autofs 
-#                            script created by Peter Anvin
-# 20 Mar 2004  B. Mason      Modified to create mountpoints if they
-#                            don't already exist.
+########################################################################
 
-source /etc/sysconfig/rc
-source $rc_functions
-source /etc/sysconfig/autofs.conf
+### BEGIN INIT INFO
+# Provides: autofs
+# Required-Start: $network ypbind
+# Required-Stop: $network ypbind
+# Default-Start: 3 4 5
+# Default-Stop: 0 1 2 6
+# Short-Description: Automounts filesystems on demand
+# Description: Automounts filesystems on demand
+### END INIT INFO
 
 #
-# This function will build a list of automount commands to execute in
-# order to activate all the mount points. It is used to figure out
-# the difference of automount points in case of a reload
+# Location of the automount daemon and the init directory
 #
-function getmounts()
-{
-  if [ -f /etc/auto.master ]
-  then
-    cat /etc/auto.master | sed -e '/^#/d' -e '/^$/d'| 
-    (
-      while read dir map options
-      do
-      if [ ! -z "$dir" -a ! -z "$map" \
-        -a x$(echo "$map" | cut -c1) != 'x-' ]
-        then
-          map=$(echo "/etc/$map" | sed -e 's:^/etc//:/:')
-          options=$(echo "$options" | sed -e 's/\(^\|[ \t]\)-/\1/g')
-          if [ -x $map ]; then
-            echo "  $dir program $map $options"
-          else 
-            echo "  $dir file $map $options"
-          fi
-        fi
-      done
-    )
-  fi
+DAEMON=/usr/sbin/automount
+prog=`basename $DAEMON`
+MODULE="autofs4"
+DEVICE="autofs"
+confdir=/etc/sysconfig
+
+test -e $DAEMON || exit 0
+
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+export PATH
+
+#
+# load customized configuation settings
+#
+if [ -r $confdir/autofs ]; then
+   . $confdir/autofs
+fi
+
+. /lib/lsb/init-functions
+
+function start() {
+   log_info_msg "Starting $prog: "
+
+   # Make sure autofs4 module is loaded
+   if ! grep -q autofs /proc/filesystems
+   then
+      # Try load the autofs4 module fail if we can't
+      modprobe $MODULE >/dev/null 2>&1
+      if [ $? -eq 1 ]
+      then
+         log_failure_msg "Error: failed to load autofs4 module."
+         return 1
+      fi
+   elif ([ -f /proc/modules ] && lsmod) | grep -q autofs[^4]
+   then
+      # wrong autofs filesystem module loaded
+      log_failure_msg "Error: autofs kernel module is loaded, autofs4 required"
+      return 1
+   fi
+
+   # Check misc device
+   if [ -n "$USE_MISC_DEVICE" -a "x$USE_MISC_DEVICE" = "xyes" ]; then
+      sleep 1
+      if [ -e "/proc/misc" ]; then
+         MINOR=`awk "/$DEVICE/ {print \\$1}" /proc/misc`
+         if [ -n "$MINOR" -a ! -c "/dev/$DEVICE" ]; then
+            mknod -m 0600 /dev/$DEVICE c 10 $MINOR
+         fi
+      fi
+      if [ -x /sbin/restorecon -a -c /dev/$DEVICE ]; then
+         /sbin/restorecon /dev/$DEVICE
+      fi
+   else
+      if [ -c /dev/$DEVICE ]; then
+         rm /dev/$DEVICE
+      fi
+   fi
+
+   $prog $OPTIONS 
+   evaluate_retval
 }
 
-#
-# Show the status of configured and active mounts.
-#
-function status()
-{
-    echo "Configured Mount Points:"
-    getmounts |
-    (
-      while read dir type map options
-      do
-        echo $dir $type $map $options
-
-        if [ $type = 'file' ]
-        then
-          cat $map | sed -e '/^#/d' -e '/^$/d' |
-          (
-            while read key options location
-            do
-              echo "  $key $options $location"
-            done
-          )
-          echo ""
-        fi 
-      done
-    )
-
-    echo "Active Automount Daemons:"
-    if [ $(COLUMNS=1024 ps ax | grep "[0-9]:[0-9][0-9] $automount " | wc -w) -gt 0 ]
-    then
-      COLUMNS=1024 ps ax | grep "[0-9]:[0-9][0-9] $automount " | 
-      (
-        while read pid tt stat time command; do echo "  $command" ; done
-      )
-    else
-       echo "  None";
-    fi
-    echo ""
-
-    echo "Actively Automounted Directories:"
-    getmounts |
-    (
-      while read dir type map options
-      do
-        line=$(mount | grep -v "^automount" | grep "$dir")
-        if [ $(echo $line | wc -w) -ne 0 ]
-          then
-          echo "$line" | sed -e "s/^./  &/"  
-        fi
-      done
-    )
-    echo ""
+function stop() {
+   log_info_msg $"Stopping $prog: "
+   count=0
+   while [ -n "`pidof $prog`" -a $count -lt 15 ] ; do
+      killall -TERM $prog >& /dev/null
+      RETVAL=$?
+      [ $RETVAL = 0 -a -z "`pidof $prog`" ] || sleep 3
+      count=`expr $count + 1`
+   done
+   if [ -z "`pidof $prog`" ] ; then
+      log_success_msg2
+   else
+      log_failure_msg2
+   fi
+   return $RETVAL
 }
 
-case "$1" in 
-  start)
-    getmounts | 
-    (
-      while read dir type map options
-      do 
-        boot_mesg -n "Automounting $dir..."
-        pidfile=$(echo $dir | sed -e "y/\//-/" | sed -e "s/^-//")
-        pidpath=${piddir}/${pidroot}.${pidfile}.pid
+function restart() {
+   stop
+   start
+}
 
-        if [ ! -d "$dir" ]
-        then
-          boot_mesg -n " Creating mountpoint $dir..."
-          mkdir -p "$dir"
-        fi
+function reload() {
+   pid=`pidof $prog`
+   if [ -z $pid ]; then
+      log_failure_msg2 $"$prog not running"
+      RETVAL=1
+   else
+      kill -HUP $pid 2> /dev/null
+      log_success_msg2 $"Reloading maps"
+      RETVAL=0
+   fi
+   return $RETVAL
+}
 
-        if [ ! -e "$map" ]
-        then
-          boot_mesg "Map file $map does not exist!" ${FAILURE}
-          echo_failure
-          continue
-        fi
+RETVAL=0
 
-        if [ ! -x "$map" -a "$type" = "program" ]
-        then
-          boot_mesg "Map file $map is not executable!" ${FAILURE}
-          echo_failure
-          continue
-        fi
-
-        if [ -e "$pidpath" ]
-        then
-          boot_mesg " already running!" ${WARNING}
-          echo_warning
-        else
-          echo " "
-          $automount -p $pidpath $daemonoptions $dir $type $map $options $localoptions
-          evaluate_retval
-        fi
-      done 
-    )
-    ;;
-
-  stop)
-    # Kill all automounters listed in /var/run
-    ls ${piddir}/${pidroot}.*.pid 2>/dev/null |
-    (
-      while read pidpath
-      do
-        pid=$(cat $pidpath)
-        pidfile=$(basename $pidpath)
-        mountpoint=$(echo $pidfile | sed -e "s/^autofs\.\(.*\)\.pid$/\1/" | sed -e "y/-/\//")
-        boot_mesg "Stopping automount on /$mountpoint..."
-        kill $pid
-        evaluate_retval
-      done
-    )
-
-    # Now kill any rogue automounters (automount process w/o pid files)
-    sleep 1
-    COLUMNS=1024 ps ax | grep "[0-9]:[0-9][0-9] $automount " |
-    (
-      while read pid everything_else
-      do
-        boot_mesg "Stopping automount with pid $pid..."
-        kill $pid
-        evaluate_retval
-      done
-    )
-    ;;
-
-  restart)
-    $0 stop
-    sleep 1
-    $0 start
-    ;;
-
-  status)
-    status
-    ;;
-
-  *)
-    echo "usage: $0 {start|stop|restart|status}"
-    exit 1
-    ;;
+case "$1" in
+   start)
+      start
+      ;;
+   forcestart)
+      OPTIONS="$OPTIONS --force"
+      start
+      ;;
+   stop)
+      stop
+      ;;
+   restart)
+      restart
+      ;;
+   forcerestart)
+      OPTIONS="$OPTIONS --force"
+      restart
+      ;;
+   reload)
+      reload
+      ;;
+   *)
+      echo $"Usage: $0 {start|forcestart|stop|restart|forcerestart|reload}"
+      exit 1;
+      ;;
 esac
 
+exit $?
 
-# END
 
