Updated gpm script, various dependency fixes and text cleanups.
git-svn-id: svn://svn.linuxfromscratch.org/BLFS/trunk/bootscripts@9063 af4574ff-66df-0310-9fd7-8a98e5e911e0

diff --git a/blfs/init.d/gpm b/blfs/init.d/gpm
--- a/blfs/init.d/gpm
+++ b/blfs/init.d/gpm
@@ -1,53 +1,83 @@
 #!/bin/sh
-# Begin $rc_base/init.d/gpm
+#######################################################################
+# Begin /etc/init.d/gpm
+#
+# Description : Start GPM Console Mouse Service
+#
+# Author      : DJ Lucas - dj@linuxfromscratch.org
+#
+# Version     : LFS 7.0
+#
+########################################################################
 
-# Based on sysklogd script from LFS-3.1 and earlier.
-# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
-# GPM specific parts by Mark Hymers - markh@linuxfromscratch.org
+### BEGIN INIT INFO
+# Provides:            gpm
+# Required-Start:      $network $local_fs
+# Should-Start:
+# Required-Stop:       $local_fs $network
+# Should-Stop:
+# Default-Start:       3 4 5
+# Default-Stop:        0 1 2 6
+# Short-Description:   Starts and stops the GPM console mouse service.
+# Description:         Starts and stops the GPM console mouse service.
+# X-LFS-Provided-By:   BLFS / LFS 7.0
+### END INIT INFO
+
+. /lib/lsb/init-functions
 
 #$LastChangedBy$
 #$Date$
 
-. /etc/sysconfig/rc
-. $rc_functions
+pidfile="/run/gpm.pid"
 
-if [ -f /etc/sysconfig/mouse ]
-	then
-	. /etc/sysconfig/mouse
-fi
+[ -f /etc/sysconfig/mouse ] && source /etc/sysconfig/mouse
 
-if [ -z "$MDEVICE" ] || [ -z "$PROTOCOL" ]
-	then
-	echo "Please create an /etc/sysconfig/mouse file containing"
-	echo "MDEVICE and PROTOCOL values"
-	exit 1;
-fi
+case "${1}" in
+   start)
+      log_info_msg "Starting GPM console mouse service..."
+      if [ "${MDEVICE}" = "" -o "${PROTOCOL}" = "" ]; then
+         log_info_msg2 "invalid configuration"
+         log_failure_msg
+         exit 2
+      fi
+      start_daemon /usr/sbin/gpm -m "${MDEVICE}" -t "${PROTOCOL}" "${GPMOPTS}"
+      evaluate_retval
+      ;;
 
-case "$1" in
-	start)
-		boot_mesg "Starting gpm..."
-		loadproc /usr/sbin/gpm -m $MDEVICE -t $PROTOCOL $GPMOPTS
-		;;
+   stop)
+      log_info_msg "Stopping GPM console mouse service..."
+      killproc /usr/sbin/gpm
+      evaluate_retval
+      ;;
 
-	stop)
-		boot_mesg "Stopping gpm..."
-		killproc /usr/sbin/gpm
-		;;
+   force-reload)
+      # gpm does not honor SIGHUP, restart if running
+      kill -0 `pidofproc -p "${pidfile}" /usr/sbin/gpm` 2>/dev/null
+      if [ "${?}" = "0" ]; then
+         ${0} restart
+      else
+         log_info_msg "Force reloading GPM console mouse service..."
+         log_info_msg2 "not running"
+         log_failure_msg
+      fi
+      ;;
 
-	restart)
-		$0 stop
-		sleep 1
-		$0 start
-		;;
+   restart)
+      ${0} stop
+      sleep 1
+      ${0} start
+      ;;
 
-	status)
-		statusproc /usr/sbin/gpm
-		;;
+   status)
+      statusproc /usr/sbin/gpm
+      ;;
 
-	*)
-		echo "Usage: $0 {start|stop|restart|status}"
-		exit 1
-		;;
+   *)
+      echo "Usage: ${0} {start|stop|force-reload|restart|status}"
+      exit 1
+      ;;
 esac
 
-# End $rc_base/init.d/gpm
+exit 0
+
+# End /etc/init.d/gpm
